from utils_ import *
import matplotlib.pyplot as plt
eps = 1e-8
class Quadrotor:
    def __init__(self,
                 pos=None,
                 quat=None,
                 vel=None,
                 a_rate=None,
                 max_vel=None,):
        self.pos = np.zeros(3) if pos is None else pos.astype(float)
        self.quat = np.array([1.0, 0.0, 0.0, 0.0]) if quat is None else quat.astype(float)
        self.vel = np.zeros(3) if vel is None else vel.astype(float)
        self.a_rate = np.zeros(3) if a_rate is None else a_rate.astype(float)
        self.max_vel = 5.0 if max_vel is None else float(max_vel)

        # Maximim thrust
        self.max_thrust = 20
        h_i = 0.1 # Vertical Height Indicator

        # Input constraints
        self.max_input_value = 1.0
        self.min_input_value = 0.0

        # Quadrotor intrinsic parameters
        self.J = np.array([0.03, 0.03, 0.06])  # Nm/s^2 = kg/m^2
        self.mass = 1.0  # kg

        # Length of motor to CoG segment
        self.length = 0.47 / 2  # m

        # Positions of thrusters
        scal = 3
        h = np.cos(np.pi / 4) * self.length
        self.x_f = np.array([h, -h, -h, h])
        self.y_f = np.array([-h, -h, h, h])
        self.body_frame = np.array([(scal*h, -scal*h, 0, 1),
                       (-scal*h, -scal*h, 0, 1),
                       (-scal*h, scal*h, 0, 1),
                       (scal*h, scal*h, 0, 1),
                       (0, 0, 0, 1),
                       (0, 0, scal*h_i, 1)])

        # For z thrust torque calculation
        self.c = 0.013  # m   (z torque generated by each motor)
        self.z_l_tau = np.array([-self.c, self.c, -self.c, self.c])

        # Gravity vector
        self.g = np.array([[0], [0], [9.81]])  # m s^-2

        # Actuation thrusts
        self.u = np.array([0.0, 0.0, 0.0, 0.0])  # N


        # Drag coefficients [kg / m]
        self.rotor_drag_xy = 0.3
        self.rotor_drag_z = 0.0  # No rotor drag in the z dimension
        self.rotor_drag = np.array(
            [self.rotor_drag_xy, self.rotor_drag_xy, self.rotor_drag_z]
        )[:, np.newaxis]
        self.aero_drag = 0.08

    def reset(self,
                 pos=None,
                 quat=None,
                 vel=None,
                 a_rate=None,
                 max_vel=None):
        self.pos = np.zeros(3) if pos is None else pos.astype(float)
        self.quat = np.array([1.0, 0.0, 0.0, 0.0]) if quat is None else quat.astype(float)
        self.vel = np.zeros(3) if vel is None else vel.astype(float)
        self.a_rate = np.zeros(3) if a_rate is None else a_rate.astype(float)
        self.max_vel = 5.0 if max_vel is None else float(max_vel)


    def forward_vector_world(self):
        """
        机体前向（机体系 +X）在世界系下的单位向量。
        """
        R = self.Rotation()  # body->world
        fwd_world = R @ np.array([1.0, 0.0, 0.0])
        return fwd_world / np.linalg.norm(fwd_world)

    # get laser 无人机坐标系
    @staticmethod
    def _fibonacci_sphere(n_points):
        """
        返回形状 (n_points, 3) 的单位向量，
        均匀覆盖半球 x>=0（把 +X 当成“正前方”）。
        n_points 是精确数量。
        """
        i = np.arange(n_points)

        # 让 μ = cos(θ) 在 [0, 1] 上均匀分布
        # 对整球我们会让 μ in [-1,1]，但半球只需要 [0,1]
        # 这里用 (i+0.5)/n_points, 避免极点完全重合
        mu = (i + 0.5) / n_points  # in (0,1)
        # 这里 mu = cos(θ)，θ = arccos(mu)
        theta = np.arccos(mu)  # θ ∈ (0, π/2)

        # 方位角用黄金角步进，让样本沿着半球绕圈均匀铺开
        golden_angle = np.pi * (3.0 - np.sqrt(5.0))  # ~2.399...
        phi = i * golden_angle  # 0, g, 2g, 3g, ...

        # 把 (θ, φ) 映射到以 +X 为极轴的方向
        # x = cosθ
        # y = sinθ cosφ
        # z = sinθ sinφ
        sin_theta = np.sin(theta)
        x = np.cos(theta)
        y = sin_theta * np.cos(phi)
        z = sin_theta * np.sin(phi)

        dirs = np.stack([x, y, z], axis=1)

        # 数值安全：单位化
        # dirs /= np.linalg.norm(dirs, axis=1, keepdims=True) + 1e-12
        return dirs

    def world_minrot_x_to_velocity(self, eps=1e-9):
        """
        在世界系中构造最小旋转 R，使 e_x -> v̂（速度方向）。
        返回 R (3x3)。若速度过小则返回 I。
        """
        v = self.vel.astype(float)
        vn = np.linalg.norm(v)
        if vn < eps:
            return np.eye(3)

        a = np.array([1.0, 0.0, 0.0])  # 世界系 +X
        b = v / vn  # 目标方向 v̂

        c = float(np.clip(np.dot(a, b), -1.0, 1.0))  # cos(theta)
        if c > 1.0 - 1e-12:
            return np.eye(3)  # 已对齐

        k = np.cross(a, b)
        s = np.linalg.norm(k)  # = sin(theta)

        # 反向：e_x -> -e_x，选用稳定轴(+Z)旋转π
        if s < 1e-12 and c < 0.0:
            axis = np.array([0.0, 0.0, 1.0])
            theta = np.pi
        else:
            axis = k / (s + eps)
            theta = np.arctan2(s, c)

        K = np.array([[0, -axis[2], axis[1]],
                      [axis[2], 0, -axis[0]],
                      [-axis[1], axis[0], 0]], dtype=float)
        s_t, c_t = np.sin(theta), np.cos(theta)
        R = np.eye(3) + s_t * K + (1 - c_t) * (K @ K)
        return R

    # collision rays 世界坐标系
    def scan_forward_hemisphere(self, mapobs, radius, n_rays, dirs_body, return_all=False):
        """
        在机体前向半球（相对机体系 +X 轴）发射 n_rays 条射线，长度 radius。
        先用 obstacles_in_cube 预筛并构建局部R-tree，再逐射线求交。
        返回：
        {
            "dirs_world": (n,3) 每条射线的世界系方向单位向量
            "hit_mask":   (n,)  bool，是否命中
            "hit_points": (n,3) 命中点（未命中时填 NaN）
            "hit_dists":  (n,)  命中距离（未命中时填 NaN）
            no       "hit_ids":    (n,)  命中障碍ID（未命中时为 -1）
            "results":    list   命中详情（dict）或 None（逐条对应）
        }
        """
        p0 = self.pos.astype(float)
        # 1) 一次性预筛 + 局部索引
        _, local_idx = mapobs.obstacles_in_cube(p0, radius)

        # 2) 在机体系以 +X 为前向，采样“前半球”方向（用 Fibonacci oversample 后取前半）
        need = int(n_rays)
        # dirs_body = self._fibonacci_sphere(need)

        # 3) 转到世界系
        R = self.world_minrot_x_to_velocity()  # body->world
        dirs_world = (R @ dirs_body.T).T
        dirs_world /= np.linalg.norm(dirs_world, axis=1, keepdims=True) + 1e-12

        # 4) 逐射线求交（仅在局部R-tree中查询）
        hit_mask = np.zeros(need, dtype=bool)
        hit_points = np.full((need, 3), np.nan, dtype=float)
        hit_dists = np.full(need, radius, dtype=float)
        # hit_ids = np.full(need, -1, dtype=int)
        results = []

        for k in range(need):
            p1 = p0 + radius * dirs_world[k]
            res = mapobs.raycast_segment(p0, p1, local_idx=local_idx, return_all=return_all)
            if return_all:
                # 取最近命中（若存在）
                res0 = res[0] if len(res) > 0 else None
            else:
                res0 = res

            results.append(res0)
            if res0 is not None:
                hit_mask[k] = True
                hit_points[k] = res0
                hit_dists[k] = float(np.linalg.norm(res0 - p0))
                # hit_ids[k] = int(res0["box_index"])
            else:
                hit_points[k] = p1

        return {
            "dirs_world": dirs_world,
            "hit_mask": hit_mask,
            "hit_points": hit_points,
            "hit_dists": hit_dists,
            # "hit_ids": hit_ids,
            "results": results,
        }

    # draw collision laser
    def draw_laser(self, scan, ax):
        scan_N = 48
        scan_R = 30.0
        p0 = self.pos
        for k in range(scan_N):
            p1 = p0 + scan_R * scan["dirs_world"][k]
            if scan["hit_mask"][k]:
                hp = scan["hit_points"][k]
                ax.plot([p0[0], hp[0]], [p0[1], hp[1]], [p0[2], hp[2]], linewidth=1, color='r', alpha=0.6)
                ax.scatter(hp[0], hp[1], hp[2], s=8, c='r')
            else:
                ax.plot([p0[0], p1[0]], [p0[1], p1[1]], [p0[2], p1[2]], linewidth=1, color='gray', alpha=0.3)

        ax.scatter(p0[0], p0[1], p0[2], s=50, c='g')  # 起点

    def get_state(self):
        return [self.pos, self.quat, self.vel, self.a_rate]

    def get_control(self):
        return self.u

    def world_frame(self):
        """ position returns a 3x6 matrix
            where row is [x, y, z] column is m1 m2 m3 m4 origin h
            """
        origin = self.pos.reshape(3, 1)
        rot = self.Rotation()
        wHb = np.r_[np.c_[rot, origin], np.array([[0, 0, 0, 1]])]

        quadBodyFrame = self.body_frame.T  # (4,6) 齐次坐标
        quadWorldFrame = wHb.dot(quadBodyFrame)  # (4,6)
        world_frame = quadWorldFrame[0:3]  # 取 x,y,z
        return world_frame

    def Rotation(self):
        """
        返回当前姿态对应的旋转矩阵 R (body->world)
        """
        return q_to_rot_mat(self.quat)


    def update(self, u, dt):
        """
        Euler dynamics integration

        :param u: 4-dimensional vector with components between [0.0, 1.0] that represent the activation of each motor.
        :param dt: time differential
        """

        # Clip inputs
        for i in range(u.shape[0]):
            u[i] = max(min(u[i], self.max_input_value), self.min_input_value)
        self.u = u * self.max_thrust

        # TODO: Generate disturbance forces / torques
        # f_d = np.random.rand(3, 1)
        f_d = np.ones((3, 1))
        t_d = np.zeros((3, 1))

        x = self.get_state()

        # Euler integration
        self.pos = self.pos + dt * self.f_pos(x)
        quat = self.quat + dt * self.f_att(x)
        self.quat = unit_quat(quat)
        self.vel = self.vel + dt * self.f_vel(x, self.u, f_d)
        speed = np.linalg.norm(self.vel)
        if speed > self.max_vel:
            # 在数值上加一个很小的 eps 防止除 0
            self.vel = self.vel / (speed + eps) * self.max_vel

        self.a_rate = self.a_rate + dt * self.f_rate(x, self.u, t_d)

    def f_pos(self, x):
        """
        Time-derivative of the position vector
        :param x: 4-length array of input state with components: 3D pos, quaternion angle, 3D vel, 3D rate
        :return: position differential increment (vector): d[pos_x; pos_y; pos_z]/dt
        """

        vel = x[2]
        return vel

    def f_att(self, x):
        """
        Time-derivative of the attitude in quaternion form
        :param x: 4-length array of input state with components: 3D pos, quaternion angle, 3D vel, 3D rate
        :return: attitude differential increment (quaternion qw, qx, qy, qz): da/dt
        """

        rate = x[3]
        angle_quaternion = x[1]

        return 1 / 2 * skew_symmetric(rate).dot(angle_quaternion)

    def f_vel(self, x, u, f_d):
        """
        Time-derivative of the velocity vector
        :param x: 4-length array of input state with components: 3D pos, quaternion angle, 3D vel, 3D rate
        :param u: control input vector (4-dimensional): [trust_motor_1, ..., thrust_motor_4]
        :param f_d: disturbance force vector (3-dimensional)
        :return: 3D velocity differential increment (vector): d[vel_x; vel_y; vel_z]/dt
        """

        a_thrust = np.array([[0], [0], [np.sum(u)]]) / self.mass
        angle_quaternion = x[1]

        return np.squeeze(-self.g + v_dot_q(a_thrust + f_d / self.mass, angle_quaternion))

    def f_rate(self, x, u, t_d):
        """
        Time-derivative of the angular rate
        :param x: 4-length array of input state with components: 3D pos, quaternion angle, 3D vel, 3D rate
        :param u: control input vector (4-dimensional): [trust_motor_1, ..., thrust_motor_4]
        :param t_d: disturbance torque (3D)
        :return: angular rate differential increment (scalar): dr/dt
        """
        rate = x[3]
        return np.array([
            (u.dot(self.y_f) + t_d[0] + (self.J[1] - self.J[2]) * rate[1] * rate[2]) / self.J[0],
            (-u.dot(self.x_f) + t_d[1] + (self.J[2] - self.J[0]) * rate[2] * rate[0]) / self.J[1],
            (u.dot(self.z_l_tau) + t_d[2] + (self.J[0] - self.J[1]) * rate[0] * rate[1]) / self.J[2],
        ]).squeeze()



# Quad = Quadrotor()
# laser = Quad._fibonacci_sphere(48)
# fig = plt.figure(figsize=(13, 13))
# ax = fig.add_subplot(111, projection='3d')
# scan_N = 48
# p0 = Quad.pos
# for k in range(scan_N):
#     p1 = p0 + laser[k]
#     if 1:
#         hp = p1
#         ax.plot([p0[0], hp[0]], [p0[1], hp[1]], [p0[2], hp[2]], linewidth=1, color='r', alpha=0.6)
#         ax.scatter(hp[0], hp[1], hp[2], s=8, c='r')
#
# ax.scatter(p0[0], p0[1], p0[2], s=50, c='g')  # 起点
if __name__ == "__main__":
    import numpy as np
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Line3DCollection

    Quad = Quadrotor()
    scan_N = 48
    scan_R = 30.0

    # laser: (N,3) 方向向量（Fibonacci 球面，通常已单位化；若不确定，下面会再单位化）
    laser = np.asarray(Quad._fibonacci_sphere(scan_N), dtype=float)
    p0 = np.asarray(Quad.pos, dtype=float).reshape(1, 3)

    # 单位化，避免方向向量长度不一
    norms = np.linalg.norm(laser, axis=1, keepdims=True)
    dirs = laser / np.clip(norms, 1e-9, None)

    # 若没有真实命中距离，就把每束长度设为最大量程
    L = np.full((scan_N, 1), scan_R, dtype=float)

    # 终点
    p1 = p0 + dirs * L  # (N,3)

    # 构造线段集合 (N,2,3)
    p0s = np.repeat(p0, scan_N, axis=0)
    segments = np.stack([p0s, p1], axis=1)

    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111, projection='3d')

    # 线段集合（一次性画所有射线）
    rays = Line3DCollection(segments, linewidths=1.5, colors='r', alpha=0.8)
    ax.add_collection3d(rays)

    # 端点散点（一次性）
    ax.scatter(p1[:, 0], p1[:, 1], p1[:, 2], s=12, c='r', alpha=0.9, zorder=5)

    # 起点
    ax.scatter(p0[0, 0], p0[0, 1], p0[0, 2], s=50, c='g', zorder=6)

    # 设定等比例坐标轴与范围
    all_pts = np.vstack([p0, p1])
    xyz_min = all_pts.min(axis=0)
    xyz_max = all_pts.max(axis=0)
    center = (xyz_min + xyz_max) / 2.0
    radius = (xyz_max - xyz_min).max() / 2.0
    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(center[2] - radius, center[2] + radius)
    ax.set_box_aspect([1, 1, 1])  # 等比例

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.tight_layout()
    plt.show()
